version: '3.8'
services:
  node:
    container_name: node
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    env_file: ./.env
    links:
      - mongodb
    labels:
      kompose.service.type: loadbalancer
    volumes:
       - .:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - backend
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  dbdata:
