version: "3"
services:
  server:
    container_name: server
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DB=ProjectIT
      - JWT_SECRET=SECRET
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - db
    labels:
      kompose.service.type: loadbalancer
    depends_on:
      - db
    networks:
      - backend
  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - backend
networks:
  backend:

